# Site settings
title: EENFEE
description: Website of ENFEE.
url: "https://eenfee.github.io" # the base hostname & protocol for your site
baseurl: ""

#favicon: "/assets/img/cLogo.png" # the path to your favicon, relative to the root of your site

permalink: /:categories/:title/

collections:
  research:
    output: true
    permalink: /research/:title/
  publications:
    output: true
    permalink: /publications/:title/
  media:
    output: true
    permalink: /media/:title/
  posts:
    output: true
    permalink: /blog/:title/

  blogs:
    output: true
    permalink: /blogs/:title/

  ept:
    output: true
    permalink: /blogs/study-abroad/ept/:title/

defaults:
  - scope:
      path: ""
      type: "publications"
    values:
      layout: "publication"
  - scope:
      path: ""
      type: "research"
    values:
      layout: "research"
  - scope:
      path: ""
      type: "media"
    values:
      layout: "media"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

sass:
  sass_dir: assets/css
  style: compressed

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: "highlight"
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Site settings
timezone: "Asia/Kathmandu" # set your timezone, see https://en.wikipedia.org/wiki/List_of
encoding: UTF-8


plugins:
  - jekyll-sass-converter
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-toc


# TOC Settings
toc:
 min_level: 1
 max_level: 3
 list_class: toc__list
 sublist_class: toc__sublist


# Include files and directories
include:
  - assets
  - assets/js
  - assets/css
  - assets/css/pages_css
  - _sass
  - assets/img
  - assets/images/logo

# Exclude files and directories
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .gitignore


  

compress_html:
  clippings: all
  ignore:
    envs: development









keywords: Study Abroad, Education, Scholarships, University, International Students, English Proficiency Tests, EPT, Oxford ELLT, Duolingo, PTE, IELTS, UK, Australia, Europe, USA, Canada, New Zealand, France, Germany, Japan, Malta, Dubai/UAE
lang: en, np # the language of your site (for example: en, fr, cn, ru, etc.)
#icon: ⚛️ # the emoji used as the favicon (alternatively, provide image name in /assets/img/)


last_updated: false # set to true if you want to display last updated in the footer
impressum_path: # set to path to include impressum link in the footer, use the same path as permalink in a page, helps to conform with EU GDPR
back_to_top: true # set to false to disable the back to top button


lazy_loading_images: true 

imagemagick:
  enabled: true # enables responsive images for your site (recommended, see https://github.com/alshedivat/al-folio/issues/537)
  widths:
    - 480
    - 800
    - 1400
  input_directories:
    - assets/img/
  input_formats:
    - ".jpg"
    - ".jpeg"
    - ".png"
    - ".tiff"
    - ".gif"
  output_formats:
    webp: "-quality 85"











