name: Build Jekyll site

on:
  push:
    branches:
      - main  # or 'master', use your default branch name
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'  # Specify your Ruby version

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build the site with Jekyll
        run: bundle exec jekyll build